name: ecoshard-dev
channels:
  - conda-forge
dependencies:
  - python=3.11
  - gdal
  - numpy
  - scipy
  - shapely
  - rtree
  - psutil
  - numexpr
  - retrying
  - filelock
  - cython
  - pytest
  - pip
  - pip:
      - -e .[test]
